import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { UserNav } from "./userNav";
import { buttonVariants } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import Logo from "../../public/logo.png";
import Image from "next/image";
import { getServerSession } from "next-auth/next";
import { authOptions } from "./api/auth/[...nextauth]/authOptions";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="border-b">
          <div className="container max-w-6xl py-2 flex justify-between items-center">
            <div className="flex items-center gap-4">
              <Image src={Logo} alt="App's logo" width={50} priority={true} />
              <Input
                type="search"
                placeholder="Search..."
                className="md:w-[300px]"
              />
            </div>
            {!session ? (
              <Link
                href="/api/auth/signin"
                className={buttonVariants({ variant: "default" })}
              >
                Sign In
              </Link>
            ) : (
              <UserNav {...session} />
            )}
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
